name: Daily Automated Scripts

on:
  schedule:
    - cron: '0 8 * * *'   # 8 AM
    - cron: '0 20 * * *'  # 8 PM
  workflow_dispatch:      # Allow to run this file manually

jobs:
  run-autosandbox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Dealabs Script
        run: node api/autosandbox.js

  run-autovinted:
    needs: run-autosandbox
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Vinted Script
        run: node api/autovinted.js
